image: maven:3.6.1


pipelines:
  branches:
    master:
      - step:
          name: Create Artifact
          caches:
            - maven
          script:
            - mvn -B package
          artifacts:
            - target/**

      - step:
          name: Push docker image to the Heroku
          deployment: Production
          services:
            - docker
          script:
            - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
            - heroku container:login
            - heroku container:push web -a [heroku-app-name]
            - heroku container:release web -a [heroku-app-name]
